export const IMPORT_COLUMNS = [
  { csv: "date",                 db: "date" as const },
  { csv: "drinks",               db: "sales_drinks_net" as const },
  { csv: "ticket",               db: "sales_ticket_net" as const },
  { csv: "snack",                db: "sales_snack_net" as const },
  { csv: "goodies",              db: "sales_goodies_net" as const },
  { csv: "card_surcharge",       db: "sales_card_surcharge" as const },
  { csv: "vat_7",                db: "vat_7" as const },
  { csv: "payment_cash",         db: "payment_cash" as const },
  { csv: "payment_scan",         db: "payment_scan" as const },
  { csv: "payment_credit_card",  db: "payment_credit_card" as const },
  { csv: "staff_food_cash",      db: "exp_staff_food_cash" as const },
  { csv: "drinks_cash",          db: "exp_drinks_cash" as const },
  { csv: "goodies_cash",         db: "exp_goodies_cash" as const },
  { csv: "animals_cash",         db: "exp_animals_cash" as const },
  { csv: "supply_cash",          db: "exp_supply_cash" as const },
  { csv: "boss_fees_cash",       db: "exp_boss_fees_cash" as const },
  { csv: "other_cash",           db: "exp_other_cash" as const },
  { csv: "makro_bank",           db: "exp_makro_bank" as const },
  { csv: "other_bank",           db: "exp_other_bank" as const },
  { csv: "salary_cash",          db: "hr_salary_cash" as const },
  { csv: "salary_bank",          db: "hr_salary_bank" as const },
  { csv: "challenge_cash",       db: "hr_challenge_cash" as const },
  { csv: "service_charge_cash",  db: "hr_service_charge_cash" as const },
  { csv: "accompte_cash",        db: "hr_accompte_cash" as const },
  { csv: "cash_end_day",         db: "cash_end_day" as const },
  { csv: "cash_to_boss",         db: "cash_to_boss" as const },
  { csv: "cash_safe",            db: "cash_safe" as const },
  { csv: "notes",                db: "notes" as const },
];

export const REQUIRED_IMPORT_HEADERS = IMPORT_COLUMNS.map((c) => c.csv);
