import type { CatalogEndpoint } from "./types";

export const LOYVERSE_CATALOG: CatalogEndpoint[] = [
  {
    id: "stores",
    path: "/stores",
    label: "Stores",
    description: "All Loyverse stores — map store_id to Nexus locations.",
    relevance: "high",
    listKey: "stores",
  },
  {
    id: "receipts",
    path: "/receipts",
    label: "Receipts",
    description: "Sales receipts with line items, payments, tax, and surcharges.",
    relevance: "high",
    listKey: "receipts",
    supportsDateFilter: true,
    supportsStoreFilter: true,
  },
  {
    id: "categories",
    path: "/categories",
    label: "Categories",
    description: "Product categories — used to map sales into accounting buckets.",
    relevance: "high",
    listKey: "categories",
  },
  {
    id: "items",
    path: "/items",
    label: "Items",
    description: "Product catalog with category_id per item.",
    relevance: "high",
    listKey: "items",
  },
  {
    id: "payment_types",
    path: "/payment_types",
    label: "Payment types",
    description: "Cash, card, QR — map to payment_cash / scan / credit_card.",
    relevance: "high",
    listKey: "payment_types",
  },
  {
    id: "taxes",
    path: "/taxes",
    label: "Taxes",
    description: "Tax definitions — compare with manual vat_7 entry.",
    relevance: "high",
    listKey: "taxes",
  },
  {
    id: "shifts",
    path: "/shifts",
    label: "Shifts",
    description: "Employee shift records.",
    relevance: "medium",
    listKey: "shifts",
    supportsDateFilter: true,
    supportsStoreFilter: true,
  },
  {
    id: "employees",
    path: "/employees",
    label: "Employees",
    description: "Staff linked to receipts.",
    relevance: "medium",
    listKey: "employees",
  },
  {
    id: "customers",
    path: "/customers",
    label: "Customers",
    description: "Customer records and loyalty points.",
    relevance: "medium",
    listKey: "customers",
  },
  {
    id: "discounts",
    path: "/discounts",
    label: "Discounts",
    description: "Discount rules applied on receipts.",
    relevance: "medium",
    listKey: "discounts",
  },
  {
    id: "inventory",
    path: "/inventory",
    label: "Inventory",
    description: "Stock levels — low priority for current accounting model.",
    relevance: "low",
    listKey: "inventory",
  },
  {
    id: "suppliers",
    path: "/suppliers",
    label: "Suppliers",
    description: "Supplier records — not used in daily_entries today.",
    relevance: "low",
    listKey: "suppliers",
  },
  {
    id: "webhooks",
    path: "/webhooks",
    label: "Webhooks",
    description: "Webhook subscriptions for real-time sync (future).",
    relevance: "low",
    listKey: "webhooks",
  },
];

export function getCatalogEndpoint(id: string): CatalogEndpoint | undefined {
  return LOYVERSE_CATALOG.find((e) => e.id === id);
}
