"use client";
import { useCallback, useEffect, useState } from "react";
import { PlusIcon } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button"; import { Card } from "@/components/ui/card"; import { DateInput } from "@/components/ui/date-input"; import { PageHeader } from "@/components/ui/page-header";
import { FinanceScopeSelector } from "./FinanceScopeSelector"; import { DEFAULT_FINANCE_SCOPE, type FinanceScope } from "@/modules/finance/scope";
type Cost = { id:string; label:string; category:string; cadence:string; estimated_amount:number; effective_from:string; effective_to:string|null; is_active:boolean; finance_cost_actuals?:{amount:number}[] }; type Location={id:string;name:string};
const empty={label:"",category:"rent",estimated_amount:"",cadence:"monthly",effective_from:new Date().toISOString().slice(0,10),effective_to:"",actual_amount:"",service_from:"",service_to:"",reason:""};
const field:React.CSSProperties={height:34,border:"1px solid var(--line-strong)",borderRadius:"var(--r-sm)",background:"var(--bg)",color:"var(--fg)",padding:"0 10px",fontSize:13,width:"100%"};
export function RecurringCostsClient(){
 const[scope,setScope]=useState<FinanceScope>(DEFAULT_FINANCE_SCOPE); const[locations,setLocations]=useState<Location[]>([]); const[costs,setCosts]=useState<Cost[]>([]); const[canManage,setCanManage]=useState(false); const[showForm,setShowForm]=useState(false); const[form,setForm]=useState(empty); const[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{const q=scope.type==="location"&&scope.locationId?`?location_id=${scope.locationId}`:"";const r=await fetch(`/api/finance/recurring-costs${q}`,{cache:"no-store"});const j=await r.json();if(!r.ok){toast.error(j.error??"Unable to load recurring costs");return}setLocations(j.locations);setCosts(j.costs);setCanManage(j.canManage)},[scope]); useEffect(()=>{void load()},[load]);
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);try{const r=await fetch("/api/finance/recurring-costs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,location_id:scope.type==="location"?scope.locationId:null,estimated_amount:Number(form.estimated_amount),actual_amount:form.actual_amount===""?undefined:Number(form.actual_amount)})});const j=await r.json();if(!r.ok)throw new Error(j.error??"Unable to save cost");setForm(empty);setShowForm(false);toast.success("Recurring cost saved");await load()}catch(error){toast.error(error instanceof Error?error.message:"Unable to save cost")}finally{setSaving(false)}}
 return <div style={{display:"flex",flexDirection:"column",gap:16}}><PageHeader eyebrow="Finance" title="Recurring costs" subtitle="The contract register for rent, utilities and other fixed commitments." actions={canManage?<Button size="sm" onClick={()=>setShowForm(v=>!v)}><PlusIcon size={14}/>Add cost</Button>:null}/><Card style={{flexDirection:"row",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:12}}><FinanceScopeSelector value={scope} locations={locations} onChange={setScope}/><span style={{color:"var(--fg-4)",fontSize:12}}>{canManage?"Owner editing":"Read only"}</span></Card>
 {showForm?<Card><form onSubmit={save} style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:12}}><label>Label<input required value={form.label} onChange={e=>setForm({...form,label:e.target.value})} style={field}/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} style={field}>{["rent","water","electricity","marketing","accounting","insurance","subscriptions","other"].map(v=><option key={v}>{v}</option>)}</select></label><label>Estimated amount<input required type="number" min="0" step=".01" value={form.estimated_amount} onChange={e=>setForm({...form,estimated_amount:e.target.value})} style={field}/></label><label>Frequency<select value={form.cadence} onChange={e=>setForm({...form,cadence:e.target.value})} style={field}><option value="monthly">Monthly</option><option value="annual">Annual</option><option value="one_off">One-off</option></select></label><label>Starts<DateInput required value={form.effective_from} onChange={e=>setForm({...form,effective_from:e.target.value})}/></label><label>Ends<DateInput value={form.effective_to} onChange={e=>setForm({...form,effective_to:e.target.value})}/></label><label>Actual amount<input type="number" min="0" step=".01" value={form.actual_amount} onChange={e=>setForm({...form,actual_amount:e.target.value})} style={field}/></label><label>Service from<DateInput value={form.service_from} onChange={e=>setForm({...form,service_from:e.target.value})}/></label><label>Service to<DateInput value={form.service_to} onChange={e=>setForm({...form,service_to:e.target.value})}/></label><label style={{gridColumn:"1 / -1"}}>Reason<input required value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} style={field} placeholder="Why this cost is being registered"/></label><div style={{gridColumn:"1 / -1",display:"flex",gap:8}}><Button size="sm" disabled={saving}>{saving?"Saving…":"Save cost"}</Button><Button type="button" size="sm" variant="secondary" onClick={()=>setShowForm(false)}>Cancel</Button></div></form></Card>:null}
 <Card flush><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr>{["Cost","Category","Frequency","Estimated","Actual","Period","Status"].map(label=><th key={label} style={{padding:"10px 14px",textAlign:label==="Estimated"||label==="Actual"?"right":"left",color:"var(--fg-4)",background:"var(--bg-2)"}}>{label}</th>)}</tr></thead><tbody>{costs.map(c=><tr key={c.id} style={{borderTop:"1px solid var(--line)"}}><td style={{padding:"11px 14px",fontWeight:600}}>{c.label}</td><td style={{padding:"11px 14px"}}>{c.category}</td><td style={{padding:"11px 14px"}}>{c.cadence}</td><td className="mono" style={{padding:"11px 14px",textAlign:"right"}}>฿{Number(c.estimated_amount).toLocaleString()}</td><td className="mono" style={{padding:"11px 14px",textAlign:"right"}}>{c.finance_cost_actuals?.[0]?`฿${Number(c.finance_cost_actuals[0].amount).toLocaleString()}`:"—"}</td><td style={{padding:"11px 14px"}}>{c.effective_from}{c.effective_to?` → ${c.effective_to}`:""}</td><td style={{padding:"11px 14px",color:c.is_active?"var(--good)":"var(--fg-4)"}}>{c.is_active?"Active":"Inactive"}</td></tr>)}</tbody></table>{costs.length===0?<p style={{padding:28,textAlign:"center",color:"var(--fg-4)"}}>No recurring costs in this scope. Add the first contract or commitment.</p>:null}</div></Card></div>}
