"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button"; import { Card } from "@/components/ui/card"; import { DateInput } from "@/components/ui/date-input"; import { PageHeader } from "@/components/ui/page-header";
import { FinanceScopeSelector } from "./FinanceScopeSelector"; import { DEFAULT_FINANCE_SCOPE, type FinanceScope } from "@/modules/finance/scope";
type Location={id:string;name:string}; type Setting={id:string;location_id:string;service_charge_rate_pct:number;operational_start_date:string|null}; const field:React.CSSProperties={height:34,border:"1px solid var(--line-strong)",borderRadius:"var(--r-sm)",background:"var(--bg)",color:"var(--fg)",padding:"0 10px",fontSize:13,width:"100%"};
export function ShopSettingsClient(){const[scope,setScope]=useState<FinanceScope>(DEFAULT_FINANCE_SCOPE);const[locations,setLocations]=useState<Location[]>([]);const[settings,setSettings]=useState<Setting[]>([]);const[canManage,setCanManage]=useState(false);const[rate,setRate]=useState("");const[start,setStart]=useState("");const[reason,setReason]=useState("");const[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{const r=await fetch("/api/finance/shop-settings",{cache:"no-store"});const j=await r.json();if(!r.ok){toast.error(j.error??"Unable to load shop settings");return}setLocations(j.locations);setSettings(j.settings);setCanManage(j.canManage)},[]);useEffect(()=>{void load()},[load]);
 const current=useMemo(()=>settings.find(s=>s.location_id===scope.locationId),[settings,scope.locationId]);useEffect(()=>{setRate(current?String(current.service_charge_rate_pct):"");setStart(current?.operational_start_date??"");setReason("")},[current]);
 async function save(e:React.FormEvent){e.preventDefault();if(!scope.locationId)return;setSaving(true);try{const r=await fetch("/api/finance/shop-settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({location_id:scope.locationId,service_charge_rate_pct:Number(rate),operational_start_date:start||null,reason})});const j=await r.json();if(!r.ok)throw new Error(j.error??"Unable to save settings");toast.success("Shop settings saved");await load()}catch(error){toast.error(error instanceof Error?error.message:"Unable to save settings")}finally{setSaving(false)}}
 const visible=scope.type==="location"?locations.filter(l=>l.id===scope.locationId):locations;return <div style={{display:"flex",flexDirection:"column",gap:16}}><PageHeader eyebrow="Finance" title="Shop settings" subtitle="The shared financial rules applied consistently by each shop."/><Card><FinanceScopeSelector value={scope} locations={locations} onChange={setScope}/></Card>{scope.type==="group"?<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:12}}>{visible.map(l=>{const s=settings.find(x=>x.location_id===l.id);return <Card key={l.id} style={{gap:8}}><strong>{l.name}</strong><span style={{fontSize:12,color:"var(--fg-4)"}}>Service charge rate</span><span className="mono" style={{fontSize:22}}>{Number(s?.service_charge_rate_pct??0)}%</span><span style={{fontSize:12,color:"var(--fg-4)"}}>Opening date · {s?.operational_start_date??"Not set"}</span></Card>})}</div>:<Card><form onSubmit={save} style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:14}}><label>Service charge rate (%)<input type="number" min="0" max="100" step=".01" required value={rate} disabled={!canManage} onChange={e=>setRate(e.target.value)} style={field}/></label><label>Opening date<DateInput value={start} disabled={!canManage} onChange={e=>setStart(e.target.value)}/></label><label style={{gridColumn:"1 / -1"}}>Reason<input required value={reason} disabled={!canManage} onChange={e=>setReason(e.target.value)} style={field} placeholder="Why these settings are changing"/></label>{canManage?<div style={{gridColumn:"1 / -1"}}><Button size="sm" disabled={saving}>{saving?"Saving…":"Save settings"}</Button></div>:<p style={{gridColumn:"1 / -1",color:"var(--fg-4)",fontSize:12}}>Reports access is read-only. An owner can update financial settings.</p>}</form></Card>}</div>}
