export const DAILY_PROFIT_METHODOLOGY = {
  version: "Simplified v3 · 2026-09-03",
  formula: "Revenue − Sheet expenses excl. HR − salaries − fixed costs − service charge − challenge bonus",
  revenueFields: [
    "sales_drinks_net",
    "sales_ticket_net",
    "sales_snack_net",
    "sales_goodies_net",
    "sales_card_surcharge",
  ],
  expenseFields: [
    "exp_staff_food_cash",
    "exp_drinks_cash",
    "exp_goodies_cash",
    "exp_animals_cash",
    "exp_supply_cash",
    "exp_boss_fees_cash",
    "exp_other_cash",
    "exp_makro_bank",
    "exp_other_bank",
  ],
  excludedFields: [
    "hr_salary_cash",
    "hr_salary_bank",
    "hr_challenge_cash",
    "hr_service_charge_cash",
    "hr_accompte_cash",
  ],
  rules: [
    "Salaries, rent, electricity, water, other fixed costs and challenge bonus are entered per shop and per month (via Monthly snapshots or manual entry).",
    "Monthly amounts are spread across all calendar days of the month, in Bangkok time.",
    "Each day's service charge equals the day's revenue × the shop's rate × number of employees.",
    "Challenge bonus is the gated monthly bonus from the Challenges module, spread evenly per day.",
    "Google Sheets HR fields are excluded from the result to avoid double counting.",
    "A month without manual entry or snapshot uses zero and triggers a coverage alert.",
  ],
} as const;
